.github/workflows/pipeline.yml
We are experiencing an issue with the npm publication because the authentication does not work. This PR aims to fix this.
=> Fixing the NPM publication.

vitruvius-labs-typescript.code-workspace
=> chore: rename workspace file

packages/architectura/package.json, packages/architectura/src/_index.mts, packages/architectura/src/core/endpoint/_index.mts, packages/architectura/src/core/endpoint/definition/_index.mts, packages/architectura/src/core/endpoint/definition/enum/_index.mts, packages/architectura/src/core/execution-context/_index.mts, packages/architectura/src/core/execution-context/definition/_index.mts, packages/architectura/src/core/server/definition/enum/_index.mts, packages/architectura/src/core/server/definition/interface/_index.mts, packages/architectura/src/ddd/_index.mts, packages/architectura/src/ddd/definition/_index.mts, packages/architectura/src/definition/enum/_index.mts, packages/architectura/src/definition/type/_index.mts, packages/architectura/src/service/jwt/_index.mts, packages/architectura/src/service/jwt/definition/_index.mts, packages/architectura/src/utility/_index.mts, packages/architectura/src/utility/content-type/_index.mts, vitruvius-labs-typescript.code-workspace
=> fix: add missing things to _index files

packages/architectura/package.json, packages/architectura/src/definition/type/json-value.type.mts
=> fix: imcomplete json value

packages/architectura/package.json, packages/architectura/src/definition/_index.mts
=> fix: make json types public

packages/architectura/package.json, packages/architectura/src/ddd/base.model.mts, packages/architectura/src/ddd/base.repository.mts, packages/architectura/src/ddd/definition/interface/model-metadata.interface.mts
=> fix: bigint id

packages/architectura/package.json, packages/architectura/src/core/_index.mts, packages/architectura/src/service/jwt/_index.mts, packages/architectura/src/service/jwt/data-object/_index.mts, packages/architectura/src/service/jwt/definition/_index.mts, packages/architectura/src/service/jwt/definition/enum/jwt-constant.enum.mts, packages/architectura/src/service/jwt/definition/type/token.type.mts, packages/architectura/src/service/jwt/hook/_index.mts, packages/architectura/src/service/jwt/utility/base64-url.mts, packages/architectura/src/service/jwt/utility/compute-signature.mts, packages/architectura/src/service/jwt/utility/validate-algorithm.mts, packages/architectura/src/service/jwt/utility/validate-claims.mts, packages/architectura/src/service/jwt/utility/validate-secret.mts, packages/architectura/src/service/session/_index.mts, packages/architectura/src/service/session/entity/_index.mts, packages/architectura/src/service/session/hook/_index.mts
=> bugfix: exposed types and values

packages/architectura/package.json, packages/architectura/src/core/endpoint/endpoint.registry.mts, packages/architectura/src/core/server/server.mts
=> bugfix: dynamic import

packages/architectura/package.json, packages/architectura/src/core/endpoint/endpoint.registry.mts, packages/architectura/src/core/server/server.mts
=> fix: domain import

packages/architectura/package.json, packages/architectura/src/core/endpoint/endpoint.registry.mts, packages/architectura/src/core/server/global-configuration.mts, packages/architectura/src/core/server/server.mts, packages/architectura/src/ddd/_index.mts, packages/architectura/src/ddd/domain.registry.mts, packages/architectura/src/ddd/domain.service.mts, packages/architectura/src/service/file-system/file-system.service.mts
=> fix: extra logs

.eslintrc.json, packages/architectura/package.json, packages/architectura/src/core/endpoint/base.endpoint.mts, packages/architectura/src/core/endpoint/endpoint.registry.mts, packages/architectura/src/core/server/rich-client-request.mts, packages/architectura/src/service/logger/logger.service.mts, packages/architectura/src/utility/json/json-utility.mts
=> bugfix: load endpoints when added

packages/architectura/package.json, packages/architectura/src/core/endpoint/endpoint.registry.mts
=> feat: ignore abstract endpoints

packages/architectura/package.json, packages/architectura/src/service/logger/logger.service.mts
=> fix: output validation error tree

packages/architectura/package.json, packages/architectura/src/core/server/rich-server-response.mts
=> fix: response sending

packages/aws-s3/package.json, packages/aws-s3/src/service/s3.service.mts
=> chore: tidying

packages/architectura/package.json, packages/architectura/src/core/server/rich-server-response.mts
=> fix: private lock check

.eslintrc.json, .github/workflows/pipeline.yml, packages/architectura/src/utility/json/json-utility.mts, packages/toolbox/.c8rc.json, packages/toolbox/.eslintrc.json, packages/toolbox/LICENSE, packages/toolbox/package.json, packages/toolbox/src/_index.mts, packages/toolbox/src/utility/_index.mts, packages/toolbox/src/utility/indent/_index.mts, packages/toolbox/src/utility/indent/indent.utility.mts, packages/toolbox/src/utility/json/_index.mts, packages/toolbox/src/utility/json/definition/_index.mts, packages/toolbox/src/utility/json/definition/type/_index.mts, packages/toolbox/src/utility/json/definition/type/json-object.type.mts, packages/toolbox/src/utility/json/definition/type/json-value.type.mts, packages/toolbox/src/utility/json/json.utility.mts, packages/toolbox/stryker.conf.json, packages/toolbox/test/indent/indent-utility.spec.mts, packages/toolbox/test/json/json-utility.spec.mts, packages/toolbox/tsconfig.build.json, packages/toolbox/tsconfig.eslint.json, packages/toolbox/tsconfig.json, packages/toolbox/tsconfig.stryker.json, packages/toolbox/tsconfig.test.json, pnpm-lock.yaml, vitruvius-labs-typescript.code-workspace
=> feat: new toolbox package

packages/ts-predicate/package.json, packages/ts-predicate/src/definition/type/object-with-nullable-property.mts, packages/ts-predicate/src/definition/type/object-with-property.mts, packages/ts-predicate/src/type-assertion/assert-nullable-property.mts, packages/ts-predicate/src/type-assertion/assert-property.mts, packages/ts-predicate/src/type-guard/has-nullable-property.mts, packages/ts-predicate/src/type-guard/has-property.mts, packages/ts-predicate/test/type-assertion/assert-nullable-property.spec.mts, packages/ts-predicate/test/type-assertion/assert-property.spec.mts, packages/ts-predicate/test/type-guard/has-nullable-property.spec.mts, packages/ts-predicate/test/type-guard/has-property.spec.mts
=> feat: loosen key type to include symbol

.eslint/configuration/strict/rules.mjs, .eslint/configuration/style/rules.mjs
=> fix: remove duplicate eslint rules

.github/workflows/pipeline.yml
=> chore: bump ci node version

packages/aws-s3/.gitignore, packages/aws-s3/package.json, packages/aws-s3/src/definition/interface/s3-compute-address.interface.mts, packages/aws-s3/src/definition/interface/s3-service-instantiation.interface.mts, packages/aws-s3/src/service/s3.service.mts
This PR adds support for LocalStack within the `aws-s3` package by adding a new parameter to the constructor.
=> LocalStack support

packages/aws-s3/src/definition/interface/s3-head-object-response.interface.mts, packages/aws-s3/src/service/s3.service.mts
This PR aims to add a `headObject` to the S3Service class.
=> AWS-S3 - Add HeadObject method to S3Service

.eslint/configuration/global/ignores.mjs, .vscode/cspell.json, packages/aws-s3/.c8rc.json, packages/aws-s3/package.json, packages/aws-s3/src/definition/interface/s3-get-object-request.interface.mts, packages/aws-s3/src/service/s3.service.mts
This PR aims to support the `Range` header for the `getObjectMethod` of the `S3Service` class within the `aws-s3` package.
=> AWS-S3 - Add range support to getObject method

packages/mockingbird/README.md
Fix little mistakes in the mockinbird documentation
=> chore: fix little mistakes

.eslint/configuration/_index.mjs, .eslint/configuration/disabled/config.mjs, .eslint/configuration/disabled/rules.mjs, .eslint/configuration/strict/rules.mjs, .eslint/configuration/style/rules.mjs, .eslint/configuration/test/rules.mjs, package.json, packages/ts-predicate/test/type-hint/get-detailed-type.spec.mts
=> chore: update eslint rules, add disabled ruleset

packages/architectura/README.md, packages/architectura/_docs/domains/readme.md, packages/architectura/_docs/endpoints/authentication.md, packages/architectura/_docs/endpoints/execution_context.md, packages/architectura/_docs/endpoints/hooks.md, packages/architectura/_docs/endpoints/readme.md, packages/architectura/_docs/endpoints/registering_endpoints.md
This PR implements the very first version of the manual to use Architectura.
=> First Architectura documentation

.vscode/cspell.json, packages/architectura/_docs/endpoints/hooks.md, packages/architectura/_docs/endpoints/registering_endpoints.md, packages/architectura/package.json, packages/architectura/src/core/endpoint/base.endpoint.mts, packages/architectura/src/core/hook/_index.mts, packages/architectura/src/core/hook/definition/_index.mts, packages/architectura/src/core/hook/definition/interface/hooks.interface.mts, packages/architectura/src/core/hook/definition/type/hook-runner.type.mts, packages/architectura/src/core/hook/hook.registry.mts, packages/architectura/src/core/hook/hook.service.mts, packages/architectura/src/core/server/server.mts, packages/architectura/test/core/endpoint/base.endpoint.spec.mts, packages/architectura/test/core/hook/hook.registry.spec.mts, packages/architectura/test/core/hook/hook.service.spec.mts, packages/architectura/test/core/server/server.spec.mts
=> feat: endpoint hook constructor

.eslint/configuration/disabled/rules.mjs, .eslint/configuration/style/rules.mjs, .eslint/configuration/test/rules.mjs, package.json, pnpm-lock.yaml
=> chore: update dev dependencies

packages/architectura/package.json, packages/architectura/src/ddd/_index.mts, packages/architectura/test/ddd/simple.factory.spec.mts
=> fix: export SimpleFactory

packages/architectura/package.json, packages/architectura/src/core/server/rich-server-response.mts
=> fix: response write when encoding

packages/ts-predicate/documentation/type-assertion.md, packages/ts-predicate/documentation/type-guard.md, packages/ts-predicate/package.json, packages/ts-predicate/src/type-assertion/_index.mts, packages/ts-predicate/src/type-assertion/assert-nullish.mts, packages/ts-predicate/src/type-assertion/assert-union.mts, packages/ts-predicate/src/type-guard/_index.mts, packages/ts-predicate/src/type-guard/is-nullish.mts, packages/ts-predicate/test/type-assertion/assert-nullish.spec.mts, packages/ts-predicate/test/type-guard/is-nullish.spec.mts
=> feat: nullish predicates

packages/architectura/package.json, packages/architectura/src/ddd/generic.factory.mts, packages/architectura/src/ddd/simple.factory.mts
=> feat: make factory constructor property protected

packages/architectura/package.json, packages/architectura/src/ddd/domain.service.mts
=> fix(architectura): Used InitializeOnce instead of Initialize in auto domain discovery algorithm.

packages/ts-predicate/README.md, packages/ts-predicate/documentation/classes.md, packages/ts-predicate/documentation/type-assertion.md, packages/ts-predicate/package.json, packages/ts-predicate/src/_index.mts, packages/ts-predicate/src/type-assertion/_index.mts, packages/ts-predicate/src/type-assertion/utils/validation-error.mts, packages/ts-predicate/src/type-assertion/utils/validation-result.mts, packages/ts-predicate/src/type-assertion/utils/validator.mts, packages/ts-predicate/test/type-assertion/validation-result.spec.mts, packages/ts-predicate/test/type-assertion/validator.spec.mts
=> feat: Validator utility class

packages/architectura/package.json, packages/architectura/src/core/endpoint/base.endpoint.mts, packages/architectura/src/core/hook/hook.service.mts, packages/architectura/src/core/server/_index.mts, packages/architectura/src/core/server/definition/interface/_index.mts, packages/architectura/src/core/server/definition/interface/http-error-instantiation.interface.mts, packages/architectura/src/core/server/http-error.mts, packages/architectura/src/core/server/server.mts, packages/architectura/src/service/jwt/utility/compute-signature.mts, packages/architectura/test/core/endpoint/base.endpoint.spec.mts, packages/architectura/test/core/hook/hook.service.spec.mts, packages/architectura/test/core/server/server.spec.mts, packages/architectura/test/service/jwt/data-object/jwt.factory.spec.mts
=> feat: HTTPError class

packages/architectura/package.json, packages/architectura/src/ddd/base.repository.mts, packages/architectura/test/ddd/base.repository.spec.mts
=> feat: repository pre/post hooks

packages/architectura/package.json, packages/architectura/src/core/endpoint/base.endpoint.mts, packages/architectura/src/core/endpoint/definition/interface/base-endpoint-typing.interface.mts, packages/architectura/src/definition/_index.mts, packages/architectura/src/definition/type/_index.mts, packages/architectura/test/core/endpoint/base.endpoint.spec.mts
- list properties explicitly
- narrow their respective types
- fix some issues when extracting type
=> fix: improve BaseEndpoint typing

packages/architectura/package.json, packages/architectura/src/ddd/base.repository.mts
=> fix: destroyed entity metadata
